//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectiveValues) DeepCopyInto(out *ObjectiveValues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectiveValues.
func (in *ObjectiveValues) DeepCopy() *ObjectiveValues {
	if in == nil {
		return nil
	}
	out := new(ObjectiveValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationSolution) DeepCopyInto(out *OptimizationSolution) {
	*out = *in
	out.Objectives = in.Objectives
	if in.ReplicaSetMovements != nil {
		in, out := &in.ReplicaSetMovements, &out.ReplicaSetMovements
		*out = make([]ReplicaSetMovement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationSolution.
func (in *OptimizationSolution) DeepCopy() *OptimizationSolution {
	if in == nil {
		return nil
	}
	out := new(OptimizationSolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSetDistribution) DeepCopyInto(out *ReplicaSetDistribution) {
	*out = *in
	if in.NodeDistribution != nil {
		in, out := &in.NodeDistribution, &out.NodeDistribution
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSetDistribution.
func (in *ReplicaSetDistribution) DeepCopy() *ReplicaSetDistribution {
	if in == nil {
		return nil
	}
	out := new(ReplicaSetDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSetMovement) DeepCopyInto(out *ReplicaSetMovement) {
	*out = *in
	if in.TargetDistribution != nil {
		in, out := &in.TargetDistribution, &out.TargetDistribution
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AvailableSlots != nil {
		in, out := &in.AvailableSlots, &out.AvailableSlots
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ScheduledCount != nil {
		in, out := &in.ScheduledCount, &out.ScheduledCount
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSetMovement.
func (in *ReplicaSetMovement) DeepCopy() *ReplicaSetMovement {
	if in == nil {
		return nil
	}
	out := new(ReplicaSetMovement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingHint) DeepCopyInto(out *SchedulingHint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingHint.
func (in *SchedulingHint) DeepCopy() *SchedulingHint {
	if in == nil {
		return nil
	}
	out := new(SchedulingHint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingHint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingHintList) DeepCopyInto(out *SchedulingHintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulingHint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingHintList.
func (in *SchedulingHintList) DeepCopy() *SchedulingHintList {
	if in == nil {
		return nil
	}
	out := new(SchedulingHintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingHintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingHintSpec) DeepCopyInto(out *SchedulingHintSpec) {
	*out = *in
	if in.ClusterNodes != nil {
		in, out := &in.ClusterNodes, &out.ClusterNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OriginalReplicaSetDistribution != nil {
		in, out := &in.OriginalReplicaSetDistribution, &out.OriginalReplicaSetDistribution
		*out = make([]ReplicaSetDistribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Solutions != nil {
		in, out := &in.Solutions, &out.Solutions
		*out = make([]OptimizationSolution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingHintSpec.
func (in *SchedulingHintSpec) DeepCopy() *SchedulingHintSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingHintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingHintStatus) DeepCopyInto(out *SchedulingHintStatus) {
	*out = *in
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingHintStatus.
func (in *SchedulingHintStatus) DeepCopy() *SchedulingHintStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulingHintStatus)
	in.DeepCopyInto(out)
	return out
}
